# https://docs.netlify.com/configure-builds/file-based-configuration/
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend/"

[context.master]
  publish = "frontend/build/"
  command = "npm install && npm run build"